nelmio_api_doc:
  documentation:
    info:
      title: Ide Challenge API
      description: Demo API
      version: 1.0.0
  areas: # to filter documented areas
    default:
      path_patterns: [ ^/api ]